"""Describe every published file in data/processed/datapackage.json.

A Frictionless Data Package (https://specs.frictionlessdata.io/data-package/):
one resource per published table, with its CSV path, the JSON copy beside it,
its row count, every field with a type inferred from the values and, for the
fields this pipeline derives, what the field means. Each resource names the
sources its rows come from and their terms, so a downstream user can see what
attribution a reuse needs without reading the README.

Regenerated by every build from the files just written, so it cannot drift
from them. It carries no timestamp or hash: a build that changes nothing
rewrites it byte for byte (data/snapshots/manifest.csv keeps the hashes).
"""
from __future__ import annotations

import csv
from pathlib import Path

SOURCES = {
    "sabin": {"title": "Sabin Center for Climate Change Law, Opposition to Renewable Energy Facilities in "
                       "the United States (June 2025 and September 2026 editions)",
              "path": "https://climate.law.columbia.edu/content/opposition-renewable-energy-facilities-united-states-september-2026-edition",
              "license": "Reuse terms not stated; cited as the compiled source of each row"},
    "moratorium_nation": {"title": "Moratorium Nation (mjbommar/moratorium-data-2026)",
                          "path": "https://github.com/mjbommar/moratorium-data-2026",
                          "license": "CC-BY-4.0"},
    "nrel": {"title": "NREL U.S. Wind and Solar Siting Regulation and Zoning Ordinances (2025), "
                      "DOI 10.25984/3363758 and 10.25984/3363739",
             "path": "https://data.openei.org/submissions/8519", "license": "CC-BY-4.0"},
    "facilities": {"title": "EIA-860M; U.S. Wind Turbine Database (USGS, LBNL, ACP); U.S. Large-Scale Solar "
                            "Photovoltaic Database (USGS, LBNL)",
                   "path": "https://www.eia.gov/electricity/data/eia860m/",
                   "license": "U.S. government work, public domain"},
    "review": {"title": "This repository's reviewed rows (data/review/), each with its own evidence URL",
               "path": "https://github.com/pricephillips/renewable-opposition", "license": "see each evidence URL"},
    "census": {"title": "U.S. Census Bureau 2024 county boundaries", "path": "https://www.census.gov/",
               "license": "U.S. government work, public domain"},
}

RESOURCES = {
    "restrictions": ("Local and state laws that constrain renewable deployment, one row per technology "
                     "of one instrument.", ["sabin", "moratorium_nation", "nrel", "review"]),
    "contested_projects": ("Project-level opposition, one row per technology of one project, with the "
                           "plant the project matches in the federal inventories.",
                           ["sabin", "review", "facilities"]),
    "cases": ("Litigation and formal proceedings with a court record.", ["sabin", "review"]),
    "siting_standards": ("Every feature of a local wind or solar siting ordinance in NREL's 2025 databases.",
                         ["nrel"]),
    "state_policies": ("State siting law, verified against the statute.", ["review"]),
    "state_policies_held": ("State siting law rows held for review, with the reason.", ["review"]),
    "county_summary": ("One row per county: published records counted by instrument, and how the "
                       "county stands (record, negative check or none).",
                       ["sabin", "moratorium_nation", "nrel", "review", "census"]),
    "sources": ("One row per cited source document, with its Internet Archive snapshot.", ["review"]),
    "group_registry": ("Opposition groups named in the records, with the sources that name them.",
                       ["sabin", "review"]),
}

DESCRIPTIONS = {
    "id": "Stable record id; never renumbered between builds.",
    "instrument_id": "One ordinance, moratorium, project or case. Count these, not rows.",
    "source_id": "Hash of the normalized source URL; joins sources.csv.",
    "severity_score": "1 mild friction, 2 material burden, 3 likely de facto ban, 4 moratorium or ban "
                      "(restrictions); 4 blocked to 1 advanced (contested projects).",
    "severity_basis": "The rule that set severity_score.",
    "scope": "renewables_only, or multi_sector_data_centers when the instrument also covers data centers.",
    "evidence_level": "Best evidence behind the row: primary_source, confirmed, court_record, compiled_record, "
                      "compiled_flagged, report_citation.",
    "verification": "verified (the instrument, minutes, a read news article or a court record backs it), "
                    "located (primary source found, not yet read) or unverified.",
    "county_fips": "The one county a county-level record covers; the county the map paints.",
    "county_fips_all": "Every county the record touches, semicolon-separated.",
    "county_fips_method": "How county_fips_all was found: name, names, point, place, place_text, override.",
    "outcome": "blocked_confirmed, blocked_unverified, restricted_conditional, advanced_confirmed, "
               "advanced_unverified, pending or needs_review.",
    "finality_evidence": "What backs the outcome: court_ruling, resolution, lead, outcome_label_only or none.",
    "facility_match": "strong when the project matches one plant in EIA-860M, USWTDB or USPVDB by name, county "
                      "and size (scripts/facility_matches.py). Never changes the outcome.",
    "facility_ids": "The matched plant's rows in data/reference/facilities.csv.",
    "facility_status": "What the inventory records for the plant: operating, under_construction, planned, "
                       "canceled_or_postponed or retired.",
    "facility_note": "The inventory entry the match rests on, in words.",
    "facility_conflict": "Set when the plant's status contradicts the published outcome.",
    "coverage": "record (anything published), negative_check (checked, nothing found) or none (not looked at).",
}


def _type(values: list[str]) -> str:
    vals = [v for v in values if v != ""]
    if not vals:
        return "string"
    try:
        for v in vals:
            int(v)
        return "integer"
    except ValueError:
        pass
    try:
        for v in vals:
            float(v)
        return "number"
    except ValueError:
        return "string"


def _resource(processed: Path, name: str) -> dict | None:
    path = processed / f"{name}.csv"
    if not path.exists():
        return None
    with path.open(newline="", encoding="utf-8") as f:
        reader = csv.reader(f)
        header = next(reader, [])
        cols: list[list[str]] = [[] for _ in header]
        rows = 0
        for row in reader:
            rows += 1
            for i, v in enumerate(row[:len(header)]):
                cols[i].append(v)
    desc, sources = RESOURCES[name]
    fields = []
    for col, values in zip(header, cols):
        field = {"name": col, "type": _type(values)}
        if col in DESCRIPTIONS:
            field["description"] = DESCRIPTIONS[col]
        fields.append(field)
    res = {"name": name.replace("_", "-"), "path": f"{name}.csv", "format": "csv", "mediatype": "text/csv",
           "encoding": "utf-8", "description": desc, "rows": rows, "schema": {"fields": fields},
           "sources": [SOURCES[s] for s in sources]}
    if (processed / f"{name}.json").exists():
        res["json_path"] = f"{name}.json"
    return res


def build(processed: Path) -> dict:
    resources = [r for r in (_resource(processed, n) for n in RESOURCES) if r]
    return {
        "name": "renewable-opposition",
        "title": "Local opposition to renewable energy facilities in the United States",
        "description": ("Restrictions, contested projects, cases, NREL siting standards and state siting law, "
                        "each row traceable to its source. Count instrument_id, not rows; restrictions that "
                        "also cover data centers are a separate figure. The numbers to quote are in "
                        "headline_metrics.json."),
        "homepage": "https://github.com/pricephillips/renewable-opposition",
        "sources": list(SOURCES.values()),
        "resources": resources,
    }
