"""Headline numbers, counted by instrument. Pure functions: no I/O.

build_seed_outputs.py writes the result to data/processed/headline_metrics.json
and headline_metrics.md on every build. Any number quoted outside this
repository should come from those files, not from counting rows: a seed row is
one technology of one instrument (classify.instrument_id), so row counts
overstate how many ordinances, moratoria or projects there are.

Rules
  - One instrument counts once, whatever technologies it covers. Its severity
    is the highest of its rows (in practice they agree).
  - Restrictions are split by scope. The headline figure is renewables_only;
    multi_sector_data_centers is reported beside it, never folded in.
    data_center_only instruments are quarantined by qc_gate and never counted.
  - Every count is also broken down by evidence_level, so a reader can see how
    much of a number rests on a primary source, and by verification
    (classify.verification): verified, located or unverified under the
    evidence standard. An instrument counts as verified only when every one
    of its rows is (in practice they agree).
"""
from __future__ import annotations

from collections import Counter

SEVERE = {3, 4}


def _instruments(rows: list[dict]) -> dict[str, dict]:
    """instrument_id -> a representative row carrying the max severity and
    the union of technologies."""
    out: dict[str, dict] = {}
    for r in rows:
        iid = r.get("instrument_id") or r.get("id")
        cur = out.get(iid)
        sev = r.get("severity_score") or 0
        techs = {t for t in str(r.get("technology") or "").split(";") if t}
        if cur is None:
            out[iid] = {**r, "severity_score": sev, "_techs": techs}
        else:
            cur["severity_score"] = max(cur["severity_score"] or 0, sev)
            cur["_techs"] |= techs
    return out


VERIFICATION_RANK = {"verified": 0, "located": 1, "unverified": 2}


def _instrument_verification(rows: list[dict]) -> dict[str, str]:
    """instrument_id -> its weakest verification across rows."""
    out: dict[str, str] = {}
    for r in rows:
        iid = r.get("instrument_id") or r.get("id")
        v = r.get("verification") or "unverified"
        if iid not in out or VERIFICATION_RANK.get(v, 2) > VERIFICATION_RANK.get(out[iid], 2):
            out[iid] = v
    return out


def _counter(items, key) -> dict[str, int]:
    return dict(sorted(Counter(key(i) or "" for i in items).items()))


def compute(datasets: dict[str, list[dict]]) -> dict:
    out: dict = {}
    rows = datasets.get("restrictions", [])
    inst = _instruments(rows)
    for iid, v in _instrument_verification(rows).items():
        inst[iid]["verification"] = v
    by_scope: dict[str, dict] = {}
    for sc in ("renewables_only", "multi_sector_data_centers"):
        group = [i for i in inst.values() if i.get("scope") == sc]
        by_scope[sc] = {
            "instruments": len(group),
            "severe_instruments": sum(1 for i in group if i["severity_score"] in SEVERE),
            "states": len({i.get("state") for i in group if i.get("state")}),
            "by_status": _counter(group, lambda i: i.get("status")),
            "by_technology": dict(sorted(Counter(t for i in group for t in i["_techs"]).items())),
            "by_evidence_level": _counter(group, lambda i: i.get("evidence_level")),
            "by_verification": _counter(group, lambda i: i.get("verification")),
        }
    out["restrictions"] = {"rows": len(rows), "instruments": len(inst), "by_scope": by_scope}

    rows = datasets.get("contested_projects", [])
    inst = _instruments(rows)
    for iid, v in _instrument_verification(rows).items():
        inst[iid]["verification"] = v
    out["contested_projects"] = {
        "rows": len(rows),
        "projects": len(inst),
        "confirmed_outcomes": sum(1 for i in inst.values()
                                  if str(i.get("outcome") or "").endswith("_confirmed")),
        "by_outcome": _counter(inst.values(), lambda i: i.get("outcome")),
        "by_evidence_level": _counter(inst.values(), lambda i: i.get("evidence_level")),
        "by_verification": _counter(inst.values(), lambda i: i.get("verification")),
    }

    rows = datasets.get("cases", [])
    inst = _instruments(rows)
    for iid, v in _instrument_verification(rows).items():
        inst[iid]["verification"] = v
    out["cases"] = {
        "rows": len(rows),
        "cases": len(inst),
        "by_case_status": _counter(inst.values(), lambda i: i.get("case_status")),
        "by_verification": _counter(inst.values(), lambda i: i.get("verification")),
    }
    return out


def render(m: dict) -> str:
    r = m["restrictions"]
    ren, multi = r["by_scope"]["renewables_only"], r["by_scope"]["multi_sector_data_centers"]
    c, k = m["contested_projects"], m["cases"]
    lines = [
        "# Headline metrics",
        "",
        "Generated by `scripts/build_seed_outputs.py` (`scripts/headline_metrics.py`).",
        "Counted by instrument: one ordinance, moratorium, project or case counts once",
        "however many technologies it covers. Quote these, not row counts.",
        "",
        "## Restrictions",
        "",
        "| | Renewables only | Also covers data centers |",
        "|---|---:|---:|",
        f"| Instruments | {ren['instruments']} | {multi['instruments']} |",
        f"| Severe (severity 3 or 4) | {ren['severe_instruments']} | {multi['severe_instruments']} |",
        f"| States | {ren['states']} | {multi['states']} |",
    ]
    for level in sorted(set(ren["by_evidence_level"]) | set(multi["by_evidence_level"])):
        lines.append(f"| Evidence: {level} | {ren['by_evidence_level'].get(level, 0)} | "
                     f"{multi['by_evidence_level'].get(level, 0)} |")
    for v in ("verified", "located", "unverified"):
        lines.append(f"| Verification: {v} | {ren['by_verification'].get(v, 0)} | "
                     f"{multi['by_verification'].get(v, 0)} |")
    lines += [
        "",
        "Verified: checked against the instrument itself or the minutes that adopted it, opened or "
        "read in an archived copy. Located: that document is found but not yet read. Unverified: "
        "a news article or a compiled tracker locates the instrument but does not verify it.",
        "",
        f"{r['rows']} published rows describe {r['instruments']} instruments.",
        "",
        "## Contested projects",
        "",
        f"{c['projects']} projects; {c['confirmed_outcomes']} with a confirmed outcome; "
        f"{c['by_verification'].get('verified', 0)} verified (backed by a news article or court record "
        f"that was read), {c['by_verification'].get('unverified', 0)} resting on a compiled report only.",
        "",
        "| Outcome | Projects |",
        "|---|---:|",
    ]
    lines += [f"| {o} | {n} |" for o, n in c["by_outcome"].items()]
    lines += ["", "## Cases", "", f"{k['cases']} cases; {k['by_verification'].get('verified', 0)} "
              "with a court record.", "", "| Status | Cases |", "|---|---:|"]
    lines += [f"| {s or '(blank)'} | {n} |" for s, n in k["by_case_status"].items()]
    return "\n".join(lines) + "\n"
