"""Recorded "checked, nothing found" results, and the counties still to check.

An empty county in a site profile reads as silence: nothing recorded, which is
not the same as nothing found. A reviewer who searched a county and found
nothing records it here, so the profile can say what was checked and when.

data/review/negative_checks.csv          hand-edited, never published as a record
  county_fips      required: a 2024 county (geo.known)
  state, county    the county's state code and name, as a reader would write them
  scope            restrictions | projects | both
  sources_checked  required: a semicolon list of exactly what was searched (the
                   county code library, the commission minutes archive for a
                   date range, a named news search, state PSC dockets)
  checked_on       required: YYYY-MM-DD
  result           always none_found
  note, reviewer
  A row that breaks one of these rules stops the build (build_seed_outputs.py),
  as a broken seed does. A check older than STALE_DAYS prints as stale.

data/review/profile_requests.csv         written by scripts/site_profile.py
  county_fips, date. One row per county a profile is run for, per day. Never
  the requester or the purpose.

data/review/negative_check_worklist.csv  regenerated by every build
  Counties that have been profiled (profile_requests.csv) but have no
  published restriction and no negative check covering restrictions yet,
  most recent request first. A worklist only; nothing here is published.
"""
from __future__ import annotations

import re
from datetime import date
from pathlib import Path

from common import REVIEW_DIR, STATE_CODES, read_csv

CHECKS_PATH = REVIEW_DIR / "negative_checks.csv"
REQUESTS_PATH = REVIEW_DIR / "profile_requests.csv"
WORKLIST_PATH = REVIEW_DIR / "negative_check_worklist.csv"

CHECK_FIELDS = ["county_fips", "state", "county", "scope", "sources_checked", "checked_on", "result",
                "note", "reviewer"]
REQUEST_FIELDS = ["county_fips", "date"]
WORKLIST_FIELDS = ["county_fips", "state", "county", "last_requested", "requests", "suggested_sources"]
SCOPES = ("restrictions", "projects", "both")
RESULTS = ("none_found",)
STALE_DAYS = 365
_DATE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
SUGGESTED = ("county code library or ordinance page; commission minutes for the last 3 years; "
             "news search for solar, wind and battery storage; state PSC or siting dockets")


def _s(v) -> str:
    return "" if v is None else str(v).strip()


def sources(row: dict) -> list[str]:
    return [p.strip() for p in _s(row.get("sources_checked")).split(";") if p.strip()]


def covers(row: dict, scope: str) -> bool:
    """Whether a check covers 'restrictions' or 'projects'."""
    return _s(row.get("scope")) in (scope, "both")


def is_stale(row: dict, today: date | None = None) -> bool:
    try:
        checked = date.fromisoformat(_s(row.get("checked_on")))
    except ValueError:
        return True
    return ((today or date.today()) - checked).days > STALE_DAYS


def load(path: Path | None = None) -> list[dict]:
    path = path or CHECKS_PATH
    return [r for r in read_csv(path) if any(_s(v) for v in r.values())]


def validate(rows: list[dict], known, state_of=None, name: str = "negative_checks.csv") -> list[str]:
    """Errors for rows that break the rules above. known(fips) -> bool says
    whether a code is a 2024 county; state_of(fips) -> code, when given,
    checks the row's state against it."""
    errors = []
    for i, r in enumerate(rows, start=2):
        where = f"{name}: row {i}"
        fips, st, checked = _s(r.get("county_fips")), _s(r.get("state")).upper(), _s(r.get("checked_on"))
        if not (re.fullmatch(r"\d{5}", fips) and known(fips)):
            errors.append(f"{where}: county_fips {fips!r} is not a 2024 county")
            continue
        if st not in STATE_CODES or (state_of and state_of(fips) and state_of(fips) != st):
            errors.append(f"{where}: state {st!r} does not match county {fips}")
        if _s(r.get("scope")) not in SCOPES:
            errors.append(f"{where}: scope {_s(r.get('scope'))!r} must be one of {', '.join(SCOPES)}")
        if not sources(r):
            errors.append(f"{where}: sources_checked must list at least one source that was searched")
        if not _DATE.match(checked):
            errors.append(f"{where}: checked_on {checked!r} is not a YYYY-MM-DD date")
        else:
            try:
                if date.fromisoformat(checked) > date.today():
                    errors.append(f"{where}: checked_on {checked} is in the future")
            except ValueError:
                errors.append(f"{where}: checked_on {checked!r} is not a real date")
        if _s(r.get("result")) not in RESULTS:
            errors.append(f"{where}: result must be none_found")
    return errors


def worklist(requests: list[dict], checks: list[dict], restricted: set[str], name_of, state_of) -> list[dict]:
    """Profiled counties with no published restriction and no check covering
    restrictions, most recent request first."""
    checked = {_s(c.get("county_fips")) for c in checks if covers(c, "restrictions")}
    seen: dict[str, dict] = {}
    for r in requests:
        fips, when = _s(r.get("county_fips")).zfill(5), _s(r.get("date"))
        if not fips.strip("0") or fips in restricted or fips in checked:
            continue
        cur = seen.setdefault(fips, {"county_fips": fips, "state": state_of(fips), "county": name_of(fips),
                                     "last_requested": "", "requests": 0, "suggested_sources": SUGGESTED})
        cur["requests"] += 1
        cur["last_requested"] = max(cur["last_requested"], when)
    return sorted(seen.values(), key=lambda r: (r["last_requested"], r["county_fips"]), reverse=True)
